### ISSUE TITLE
About testing code

### ISSUE THREAD

**Issue by alvinlin1271320** [SamsungLabs/Noise2NoiseFlow#2]
Hi, thanks for the excellent work.
Is there have testing code that can denoise noisy image or noise modeling on my image first?
I would like to see the result of these first. :D

Thanks!

**Comment by AliMaleky7997** [comment]
Yes, this project includes two separate directories for the two works. One (Noise2NoiseFlow) is for raw RGB images. Please see instructions on how to run the model [here](https://github.com/SamsungLabs/Noise2NoiseFlow/tree/main/noise2noiseflow): 

For sRGB images, please check out the instructions in [this directory](https://github.com/SamsungLabs/Noise2NoiseFlow/tree/main/sRGB_noise_modeling). 

While there is no separate script for testing your individual image off the shelf, I believe you'd need minimal modifications in order to make them work on your own data. Especially for the Noise2NoiseFlow model, as we have a separate denoiser, you can load the model state dict from [this directory](https://github.com/SamsungLabs/Noise2NoiseFlow/tree/main/denoisers) and use your own custom data to denoise images.

**Comment by alvinlin1271320** [comment]
Thanks for these info.
I'll give it a shot.
