### ISSUE TITLE
About iso and cam

### ISSUE THREAD

**Issue by alvinlin1271320** [SamsungLabs/Noise2NoiseFlow#3]
Sorry to bother you,
I am interested in training Noise2NoiseFlow using my own dataset. However, my dataset doesn't include the values for iso and cam. Is it possible to train the model using only the images without providing these values? I encountered an error during training indicating the need for iso and cam values. If adjustments can be made to accommodate this, could you kindly guide me on which parts of the code I should modify? Thank you so much for your assistance!

**Comment by AliMaleky7997** [comment]
Hi Alvin, again sorry for my late reply.

The ISO and cam are used to separate different camera noise distributions in the model (ISO actually is used to scale noise magnitude). In case the images in your dataset have camera information, you can use those to identify camera codes. Otherwise, you might also use the same CAM and ISO value for all of your images, acknowledging the fact that it is a compromise.
