### ISSUE TITLE
About inference noise modeling

### ISSUE THREAD

**Issue by alvinlin1271320** [SamsungLabs/Noise2NoiseFlow#4]
HI!
I have completed the training of the Noise2NoiseFlow model, and the denoising performance looks very good. However, I have not been able to implement the Noise Modeling on my images. I saw that when training the NoiseFlow model, the input is "noise1" (noisy1 - denoised2), but when I inference it, I cannot input only just noise (because I only have a clean image). Is this function available in the code? 😀

Thanks!

**Comment by AliMaleky7997** [comment]
Hi Alvin, I'm sorry I didn't see this message earlier. I hope your issue is resolved by now. I'll explain here in case it's not.

If you want to train Noise Flow separately, if I remember correctly, it would ask you to give noise1 to it (which is noisy - denoised), but in case you want to run Noise2NoiseFlow on a pair of noisy images, the model first estimates the noise-free image for each of the two input noisy images (that would give you denoised1 and denoised2 given noisy1 and noisy2). Then, it would estimate the noise vectors noise1 and noise2 to be "noisy1 - denoised2" and "noisy2 - denoised1".

If your pair is a noisy-clean pair instead of noisy1-noisy2 you might want to use Noise Flow directly with noise = noisy - clean.

Hope it helps.
